#lang racket
(require redex
         "../../executionEnvironment.rkt"
         "../../Relations/fullProgs.rkt"
         "../../Desugar/parser.rkt"
         "./tests_aux.rkt")

(define (test-events_1)
  (test-suite "events_1.lua"
              (list "_G"
                    "assert"
                    "collectgarbage"
                    "getmetatable"
                    "next"
                    "pairs"
                    "pcall"
                    "print"
                    "rawequal"
                    "rawget"
                    "rawlen"
                    "rawset"
                    "setmetatable"
                    "table"
                    "tostring"
                    "table.unpack"
                    "type"
                    )))

(define (test-events_2)
  (test-suite "events_2.lua"
              (list "_G"
                    "assert"
                    "collectgarbage"
                    "getmetatable"
                    "next"
                    "pairs"
                    "pcall"
                    "print"
                    "rawequal"
                    "rawget"
                    "rawlen"
                    "rawset"
                    "setmetatable"
                    "table"
                    "tostring"
                    "table.unpack"
                    "type"
                    )))

(define (test-events_3)
  (test-suite "events_3.lua"
              (list "_G"
                    "assert"
                    "collectgarbage"
                    "getmetatable"
                    "next"
                    "pairs"
                    "pcall"
                    "print"
                    "rawequal"
                    "rawget"
                    "rawlen"
                    "rawset"
                    "setmetatable"
                    "table"
                    "tostring"
                    "table.unpack"
                    "type"
                    )))

(define (test-events_4)
  (test-suite "events_4.lua"
              (list "_G"
                    "assert"
                    "collectgarbage"
                    "getmetatable"
                    "next"
                    "pairs"
                    "pcall"
                    "print"
                    "rawequal"
                    "rawget"
                    "rawlen"
                    "rawset"
                    "setmetatable"
                    "table"
                    "tostring"
                    "table.unpack"
                    "type"
                    "debug"
                    "debug.setmetatable"
                    )))

(provide test-events_1 test-events_2 test-events_3 test-events_4)